name: First Workflow
on:
  workflow_dispatch: #event- manual trigger
    inputs:
      ansible-version:
        description: >-
          Release Version. Example : 11.1.0
        required: true
jobs:
  first-job:
    runs-on: ubuntu-latest #runner
    steps:
      - name: Split version code
        uses: xom9ikk/split@v1
        id: split
        with:
         string: ${{ inputs.ansible-version }}
         separator: .
         limit: -1
        env:
          ansible-major-version: ${{ steps.split.outputs._0 }}

      - name: Get major version
        run: echo "ANSIBLE_MAJOR=${{ steps.split.outputs._0 }}" >> $GITHUB_ENV

      # name: Define variable
        #env:
          #ansible-major-version: ${{ steps.split.outputs._0 }}

  second-job:
    needs: first-job
    name: Test stuff
    runs-on: ubuntu-latest
    steps:
        - name: Print greeting
          run: echo "Hello World $ANSIBLE_MAJOR "
        - name: Print goodbye
          run : echo "Done - bye $ansible-major-version!"

